name: Gerar imagem do HTML e atualizar README

on:
  push:
    paths:
      - 'docs/languagetable.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Puppeteer
        run: npm install puppeteer

      - name: Criar pasta assets se não existir
        run: mkdir -p assets

      - name: Gerar screenshot com Puppeteer
        run: node scripts/screenshot.js

      - name: Verificar mudanças e fazer commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/languagetable.png

          # Só faz commit se houver mudanças
          if ! git diff --cached --quiet; then
            git commit -m "Atualiza imagem do languagetable"
            git push
          else
            echo "Nenhuma mudança detectada na imagem"
          fi
