name: Gerar imagem do HTML e atualizar README

on:
  push:
    paths:
      - 'docs/languagetable.html'
      - 'scripts/screenshot.js'

jobs:
  gerar-imagem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install puppeteer

      - name: Executar script para gerar imagem
        run: node scripts/screenshot.js

      - name: Commit e push se imagem foi atualizada
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/languagetable.png
          git diff --cached --quiet || git commit -m "Atualiza imagem do languagetable"
          git push
