name: Gerar imagem do HTML e atualizar README

on:
  push:
    paths:
      - 'docs/languagetable.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install puppeteer
        run: npm install puppeteer

      - name: Gerar screenshot do HTML
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto(`file://${process.cwd()}/docs/languagetable.html`);
            await page.screenshot({ path: 'assets/languagetable.png', fullPage: true });
            await browser.close();
          })();
          EOF

      - name: Commit e push se mudou imagem
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/languagetable.png
          git diff --quiet && echo "Nenhuma mudança para commitar" || git commit -m "Atualiza imagem do languagetable"
          git push
