name: Generate Nave Animation GIF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render-and-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install puppeteer@21.3.8
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Render animation and capture as GIF
        run: |
          mkdir -p output
          node scripts/render-and-record.js

      - name: Commit generated GIF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "Sem alterações no GIF"
          else
            git add assets/nave.gif
            git commit -m "Atualiza GIF da nave animada"
            git push
          fi

      - name: Clean up temp frames
        run: rm -rf frames
